"""update user_apikey

Revision ID: 002a2827bd15
Revises: c617b9a03b09
Create Date: 2026-04-16 15:02:57.427861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002a2827bd15'
down_revision: Union[str, None] = 'c617b9a03b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_title', sa.String(length=128), nullable=True))
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('api_keys', 'key_title')
    # ### end Alembic commands ###
