"""update user role

Revision ID: 0d914ba3d9ce
Revises: 16e146f6f9ef
Create Date: 2026-04-27 19:38:38.847571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d914ba3d9ce'
down_revision: Union[str, None] = '16e146f6f9ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_start_end_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_start_end_json', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
