"""update blc

Revision ID: 1137a5bd2462
Revises: 002a2827bd15
Create Date: 2026-04-19 15:25:16.769723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1137a5bd2462'
down_revision: Union[str, None] = '002a2827bd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_payment_plans_id'), table_name='app_payment_plans')
    op.drop_table('app_payment_plans')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_table('payments')
    op.add_column('user_settings', sa.Column('location', sa.String(length=200), nullable=True))
    op.drop_column('user_settings', 'ip_city')
    op.drop_column('user_settings', 'ip_country')
    op.drop_column('user_settings', 'bio')
    op.drop_column('user_settings', 'strong_points')
    op.drop_column('user_settings', 'marital_status')
    op.drop_column('user_settings', 'gender')
    op.drop_column('user_settings', 'dowry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('dowry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('marital_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('strong_points', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('ip_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('ip_city', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('user_settings', 'location')
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('payment_type', postgresql.ENUM('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'SERVICE_FEE', 'REFUND', name='paymenttype'), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'ALIPAY', 'WECHAT', 'BALANCE', name='paymentmethod'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'EXPIRED', 'MATCHED', 'CANCELLED', 'REFUNDED', name='orderstatus'), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('app_payment_plans',
    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('features', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('maker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('app_payment_plans_pkey'))
    )
    op.create_index(op.f('ix_app_payment_plans_id'), 'app_payment_plans', ['id'], unique=False)
    # ### end Alembic commands ###
