"""update order4

Revision ID: 16e146f6f9ef
Revises: ef2b925d3c45
Create Date: 2026-04-26 20:38:03.058520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e146f6f9ef'
down_revision: Union[str, None] = 'ef2b925d3c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'profit_amount')
    # First ensure maker_id is nullable
    op.alter_column('transactions', 'maker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Update existing NULL values to 0
    op.execute("UPDATE transactions SET maker_id = 0 WHERE maker_id IS NULL")
    # Now make it NOT NULL
    op.alter_column('transactions', 'maker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'maker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('orders', sa.Column('profit_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
