"""add address1

Revision ID: 212eaba3329e
Revises: 83257d1d8287
Create Date: 2026-04-29 13:46:31.012765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '212eaba3329e'
down_revision: Union[str, None] = '83257d1d8287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(length=10), nullable=True, comment='BTC / EVM / TRON'),
    sa.Column('address', sa.String(length=116), nullable=True),
    sa.Column('derivation_index', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_addresses_address'), 'order_addresses', ['address'], unique=False)
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='USDT, TRX')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='收款地址(Base58格式)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='收款地址(Base58格式)')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='USDT, TRX')
    op.drop_index(op.f('ix_order_addresses_address'), table_name='order_addresses')
    op.drop_table('order_addresses')
    # ### end Alembic commands ###
