"""update user3s

Revision ID: 2143bed19449
Revises: dfd9c1e6cfe0
Create Date: 2026-04-22 09:39:36.045930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2143bed19449'
down_revision: Union[str, None] = 'dfd9c1e6cfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_invited_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'invited_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_invited_by_fkey'), 'users', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'parent_id')
    # ### end Alembic commands ###
