"""update model3

Revision ID: 31b7ff2b0c21
Revises: ce0e52d5f241
Create Date: 2026-04-23 16:50:12.849042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b7ff2b0c21'
down_revision: Union[str, None] = 'ce0e52d5f241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_pricing', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_pricing', 'level')
    # ### end Alembic commands ###
