"""update user

Revision ID: 4b6fa23b639d
Revises: 545990ad372f
Create Date: 2026-04-16 14:41:25.264470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b6fa23b639d'
down_revision: Union[str, None] = '545990ad372f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('CONSUME', 'RECHARGE', 'COMMISSION', name='transactiontype'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('commission_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('to_user', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_log_from_user'), 'commission_log', ['from_user'], unique=False)
    op.create_index(op.f('ix_commission_log_id'), 'commission_log', ['id'], unique=False)
    op.create_index(op.f('ix_commission_log_to_user'), 'commission_log', ['to_user'], unique=False)
    op.drop_index(op.f('ix_user_items_id'), table_name='user_items')
    op.drop_table('user_items')
    op.add_column('users', sa.Column('api_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    op.create_table('user_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_items_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_items_pkey'))
    )
    op.create_index(op.f('ix_user_items_id'), 'user_items', ['id'], unique=False)
    op.drop_index(op.f('ix_commission_log_to_user'), table_name='commission_log')
    op.drop_index(op.f('ix_commission_log_id'), table_name='commission_log')
    op.drop_index(op.f('ix_commission_log_from_user'), table_name='commission_log')
    op.drop_table('commission_log')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
