"""update order

Revision ID: 5a2a36caa3d9
Revises: 78b3b9b5e6c9
Create Date: 2026-04-26 14:34:55.162678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a2a36caa3d9'
down_revision: Union[str, None] = '78b3b9b5e6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_status')
    op.alter_column('transactions', 'maker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('transactions', 'maker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('orders', sa.Column('order_status', postgresql.ENUM('PENDING', 'CONFIRMED', 'EXPIRED', 'MATCHED', 'CANCELLED', 'REFUNDED', name='orderstatus'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
