"""update msg

Revision ID: 68120919860e
Revises: 0d914ba3d9ce
Create Date: 2026-04-28 15:32:59.441407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68120919860e'
down_revision: Union[str, None] = '0d914ba3d9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('to_user', sa.String(length=100), nullable=False),
    sa.Column('from_user', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('message_type', sa.String(length=10), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_messages_id'), 'app_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_messages_id'), table_name='app_messages')
    op.drop_table('app_messages')
    # ### end Alembic commands ###
