"""add address

Revision ID: 83257d1d8287
Revises: 68120919860e
Create Date: 2026-04-29 13:34:20.111799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83257d1d8287'
down_revision: Union[str, None] = '68120919860e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('received_amount', sa.DECIMAL(precision=18, scale=6), nullable=True, comment='实际到账金额'))
    op.add_column('orders', sa.Column('from_address', sa.String(length=100), nullable=True, comment='付款人地址(Base58格式)'))
    op.add_column('orders', sa.Column('tx_hash', sa.String(length=128), nullable=True, comment='TRON交易哈希(TXID)'))
    op.add_column('orders', sa.Column('confirmations', sa.Integer(), nullable=True, comment='当前确认数'))
    op.add_column('orders', sa.Column('required_confirmations', sa.Integer(), nullable=True, comment='TRON建议19+确认'))
    op.add_column('orders', sa.Column('payment_channel', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('callback_payload', sa.String(length=200), nullable=True))
    
    # Fill NULL values with defaults before setting NOT NULL
    op.execute("UPDATE orders SET amount = 0.0 WHERE amount IS NULL")
    op.execute("UPDATE orders SET currency = 'USDT' WHERE currency IS NULL")
    op.execute("UPDATE orders SET chain = 'TRON' WHERE chain IS NULL")
    op.execute("UPDATE orders SET to_address = '' WHERE to_address IS NULL")
    op.execute("UPDATE orders SET order_status = 'PENDING' WHERE order_status IS NULL")
    
    op.alter_column('orders', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=18, scale=6),
               nullable=False,
               comment='应收金额')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='USDT, TRX')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='TRON, ETH 等')
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='收款地址(Base58格式)')
    op.alter_column('orders', 'path_index',
               existing_type=sa.INTEGER(),
               comment='HD钱包派生索引',
               existing_nullable=True)
    op.alter_column('orders', 'contract',
               existing_type=sa.VARCHAR(length=100),
               comment='TRC20代币合约地址，原生TRX为空',
               existing_nullable=True)
    op.alter_column('orders', 'order_status',
               existing_type=sa.VARCHAR(length=20),
               comment='PENDING/DETECTED/CONFIRMING/PAID/EXPIRED/FAILED',
               existing_nullable=True)
    op.alter_column('orders', 'order_for',
               existing_type=sa.VARCHAR(length=50),
               comment='vip, chat, item',
               existing_nullable=True)
    op.create_index(op.f('ix_orders_tx_hash'), 'orders', ['tx_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tx_hash'), table_name='orders')
    op.alter_column('orders', 'order_for',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='vip, chat, item',
               existing_nullable=True)
    op.alter_column('orders', 'order_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='PENDING/DETECTED/CONFIRMING/PAID/EXPIRED/FAILED',
               existing_nullable=True)
    op.alter_column('orders', 'contract',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='TRC20代币合约地址，原生TRX为空',
               existing_nullable=True)
    op.alter_column('orders', 'path_index',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='HD钱包派生索引',
               existing_nullable=True)
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='收款地址(Base58格式)')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='USDT, TRX')
    op.alter_column('orders', 'amount',
               existing_type=sa.DECIMAL(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment=None,
               existing_comment='应收金额')
    op.drop_column('orders', 'callback_payload')
    op.drop_column('orders', 'payment_channel')
    op.drop_column('orders', 'required_confirmations')
    op.drop_column('orders', 'confirmations')
    op.drop_column('orders', 'tx_hash')
    op.drop_column('orders', 'from_address')
    op.drop_column('orders', 'received_amount')
    # ### end Alembic commands ###
