"""remove address1

Revision ID: a9e81d0c2ff9
Revises: 212eaba3329e
Create Date: 2026-04-29 16:58:23.692768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e81d0c2ff9'
down_revision: Union[str, None] = '212eaba3329e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_addresses_address'), table_name='order_addresses')
    op.drop_table('order_addresses')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='USDT, TRX')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='收款地址(Base58格式)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='收款地址(Base58格式)')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='USDT, TRX')
    op.create_table('order_addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=True),
    sa.Column('chain', sa.VARCHAR(length=10), autoincrement=True, nullable=True, comment='BTC / EVM / TRON'),
    sa.Column('address', sa.VARCHAR(length=116), autoincrement=True, nullable=True),
    sa.Column('derivation_index', sa.INTEGER(), autoincrement=True, nullable=True),
    sa.Column('used', sa.BOOLEAN(), autoincrement=True, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=True, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=True, nullable=True),
    sa.Column('memo', sa.VARCHAR(), autoincrement=True, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('order_addresses_pkey'))
    )
    op.create_index(op.f('ix_order_addresses_address'), 'order_addresses', ['address'], unique=True)
    # ### end Alembic commands ###
