"""update trans

Revision ID: be6de204ff49
Revises: 31b7ff2b0c21
Create Date: 2026-04-25 21:38:30.675625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6de204ff49'
down_revision: Union[str, None] = '31b7ff2b0c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_pricing', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('orders', sa.Column('notify_count', sa.Integer(), nullable=True))
    # First add maker_id as nullable to handle existing data
    op.add_column('transactions', sa.Column('maker_id', sa.Integer(), nullable=True))
    # Update existing records: set maker_id to user_id before dropping it
    op.execute("UPDATE transactions SET maker_id = user_id WHERE maker_id IS NULL")
    # Now make it NOT NULL
    op.alter_column('transactions', 'maker_id', nullable=False)
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_maker_id'), 'transactions', ['maker_id'], unique=False)
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'from_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('from_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_maker_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_column('transactions', 'maker_id')
    op.drop_column('orders', 'notify_count')
    op.alter_column('model_pricing', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
