"""add token usage log columns

Revision ID: c5e5ae6fcd7a
Revises: e5c2e18ed588
Create Date: 2026-05-11 11:03:05.260295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e5ae6fcd7a'
down_revision: Union[str, None] = 'e5c2e18ed588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='USDT, TRX')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='收款地址(Base58格式)')
    op.alter_column('orders', 'order_status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending/detected/confirming/success/expired/failed',
               existing_comment='PENDING/DETECTED/CONFIRMING/PAID/EXPIRED/FAILED',
               existing_nullable=True)
    op.alter_column('orders', 'pay_way',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('token_usage_log', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('token_usage_log', sa.Column('input_tokens', sa.Float(), nullable=True))
    op.add_column('token_usage_log', sa.Column('output_tokens', sa.Float(), nullable=True))
    op.add_column('token_usage_log', sa.Column('provider_cost', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('token_usage_log', sa.Column('sale_price', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('token_usage_log', sa.Column('profit', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('token_usage_log', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('token_usage_log', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_usage_log', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=True, nullable=True))
    op.drop_column('token_usage_log', 'status')
    op.drop_column('token_usage_log', 'profit')
    op.drop_column('token_usage_log', 'sale_price')
    op.drop_column('token_usage_log', 'provider_cost')
    op.drop_column('token_usage_log', 'output_tokens')
    op.drop_column('token_usage_log', 'input_tokens')
    op.drop_column('token_usage_log', 'model')
    op.alter_column('orders', 'pay_way',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'order_status',
               existing_type=sa.VARCHAR(length=20),
               comment='PENDING/DETECTED/CONFIRMING/PAID/EXPIRED/FAILED',
               existing_comment='pending/detected/confirming/success/expired/failed',
               existing_nullable=True)
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='收款地址(Base58格式)')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='USDT, TRX')
    # ### end Alembic commands ###
