"""update users43

Revision ID: ce0e52d5f241
Revises: a7f9d012e5f5
Create Date: 2026-04-23 10:11:32.215030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce0e52d5f241'
down_revision: Union[str, None] = 'a7f9d012e5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('input_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('output_price', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_pricing_id'), 'model_pricing', ['id'], unique=False)
    op.create_index(op.f('ix_model_pricing_model_name'), 'model_pricing', ['model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_pricing_model_name'), table_name='model_pricing')
    op.drop_index(op.f('ix_model_pricing_id'), table_name='model_pricing')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
