"""update users

Revision ID: dfd9c1e6cfe0
Revises: 5d23c50fb589
Create Date: 2026-04-22 08:49:57.981734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd9c1e6cfe0'
down_revision: Union[str, None] = '5d23c50fb589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_usage_log', sa.Column('request_data', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('from_user', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'from_user')
    op.drop_column('token_usage_log', 'request_data')
    # ### end Alembic commands ###
