"""update token quota

Revision ID: e4bbdd58bb87
Revises: 1137a5bd2462
Create Date: 2026-04-20 12:04:15.094459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4bbdd58bb87'
down_revision: Union[str, None] = '1137a5bd2462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('quota', sa.Float(), nullable=True),
    sa.Column('used', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_quota_user_id'), 'token_quota', ['user_id'], unique=False)
    op.drop_index(op.f('ix_token_balances_id'), table_name='token_balances')
    op.drop_index(op.f('ix_token_balances_user_id'), table_name='token_balances')
    op.drop_table('token_balances')
    op.add_column('api_keys', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_column('api_keys', 'is_revoked')
    op.drop_column('api_keys', 'referrer_id')
    op.drop_column('api_keys', 'key_title')
    op.drop_column('api_keys', 'used_tokens')
    op.drop_column('api_keys', 'quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('quota', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('used_tokens', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('key_title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.drop_column('api_keys', 'name')
    op.create_table('token_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_balances_pkey'))
    )
    op.create_index(op.f('ix_token_balances_user_id'), 'token_balances', ['user_id'], unique=False)
    op.create_index(op.f('ix_token_balances_id'), 'token_balances', ['id'], unique=False)
    op.drop_index(op.f('ix_token_quota_user_id'), table_name='token_quota')
    op.drop_table('token_quota')
    # ### end Alembic commands ###
