"""order updated1

Revision ID: e5c2e18ed588
Revises: a9e81d0c2ff9
Create Date: 2026-04-29 17:19:50.360382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c2e18ed588'
down_revision: Union[str, None] = 'a9e81d0c2ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add pay_way column with default value for existing rows
    op.add_column('orders', sa.Column('pay_way', sa.Integer(), nullable=True))
    op.execute("UPDATE orders SET pay_way = 1 WHERE pay_way IS NULL")
    
    # Alter columns - keep them nullable to avoid conflicts with existing data
    op.alter_column('orders', 'pay_way', existing_type=sa.Integer(), nullable=False)
    
    op.drop_column('orders', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=True))
    op.alter_column('orders', 'to_address',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='收款地址(Base58格式)')
    op.alter_column('orders', 'chain',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='TRON, ETH 等')
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='USDT, TRX')
    op.drop_column('orders', 'pay_way')
    # ### end Alembic commands ###
