"""update order3

Revision ID: ef2b925d3c45
Revises: 5a2a36caa3d9
Create Date: 2026-04-26 14:37:40.698616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2b925d3c45'
down_revision: Union[str, None] = '5a2a36caa3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_status', sa.String(length=20), nullable=True))
    op.alter_column('transactions', 'maker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'maker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'order_status')
    # ### end Alembic commands ###
