"""update token quota

Revision ID: fcbb1d00db97
Revises: e4bbdd58bb87
Create Date: 2026-04-20 12:31:15.082634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcbb1d00db97'
down_revision: Union[str, None] = 'e4bbdd58bb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_stream', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_log_provider'), 'token_usage_log', ['provider'], unique=False)
    op.create_index(op.f('ix_token_usage_log_request_id'), 'token_usage_log', ['request_id'], unique=True)
    op.create_index(op.f('ix_token_usage_log_user_id'), 'token_usage_log', ['user_id'], unique=False)
    op.drop_index(op.f('ix_token_quota_user_id'), table_name='token_quota')
    op.drop_table('token_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_quota',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quota', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_quota_pkey'))
    )
    op.create_index(op.f('ix_token_quota_user_id'), 'token_quota', ['user_id'], unique=False)
    op.drop_index(op.f('ix_token_usage_log_user_id'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_request_id'), table_name='token_usage_log')
    op.drop_index(op.f('ix_token_usage_log_provider'), table_name='token_usage_log')
    op.drop_table('token_usage_log')
    # ### end Alembic commands ###
